spring:
  application:
    name: app-backend-elite

  datasource:
    url: jdbc:mysql://elitezapatillas.mysql.database.azure.com:3306/almacen_elite
    username: adminelite
    password: Grupo002@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    azure:
      storage:
        account-name: demostorage939
        account-key: mqEkPXLzeaaRtfX4PZg4V0Fra8An6OzXjFPLi435bkjFT7e66teAD0IqJipkt5IiIzWVMj5ncztg+AStYdJLxQ==

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB

jwt:
  expiration: 3600000
  expiration-refresh: 86400000
  secret: VGhpc0lzQUNvbXBsZXhTdXBlclNlY3JldEtleU9mMjU2Qml0cw==

url:
  frontend: ${frontend-uri:http://localhost:5173}